### PR TITLE
Removed console.logs on files.

### PR DESCRIPTION
**Pull request by Vinicius149**
This change resolves the #7, removed most of the console.log functions. 
However, I kept the ones inside "if" blocks for safety.

### CODE REVIEW

**Comment by HallexCosta** [comment]
Thanks for your contribution @Vinicius149 

I took a look at your PR and noticed that it affects the development environment. Try restoring the `logs` in the development environment again and removing the logs **only** in the production environment.

Probably adding it to `index.tsx` before rendering the `App`, something like this:

```ts
if (process.env.NODE_ENV === 'production') {
  console.log = () => {}
  console.debug = () => {}
  console.info = () => {}
}
```

**Review by HallexCosta — CHANGES_REQUESTED** [review]
Thanks for your contribution @Vinicius149 

I took a look at your PR and noticed that it affects the development environment. Try restoring the `logs` in the development environment again and removing the logs **only** in the production environment.

Probably adding it to `index.tsx` before rendering the `App`, something like this:

```ts
if (process.env.NODE_ENV === 'production') {
  console.log = () => {}
  console.debug = () => {}
  console.info = () => {}
}
```

**Comment by Vinicius149** [comment]
This was the first time i rolled back code changes, hope it worked!
Anyway i changed the code as you suggested, maybe is gtg now.

**Review by HallexCosta — APPROVED** [review]

**Pull request merged**
